access_token = "9267|UdCDVSWUx4a2Bb0LD4idoBorOXGpuM7zoUHnoQyv"
token_type = "Bearer"
created_at = 2023-03-05T19:49:31.7076684+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
