access_token = "4573|1gL2RHsUt5WjVM7ob7lTgAd0kbZF3Mokq2aPmvIB"
token_type = "Bearer"
created_at = 2023-03-15T00:48:43.5632783+03:00

[user_data]
  id = 8732
  full_name = "Бушкова Т.В."
  user_name = "Бушкова Т.В."
  avatar = ""
  email = "service@circus.ru"
  role = "admin"
