access_token = "4703|jwqvoNNs14NXniugw1CpMfPGPRxDayo18IqrdEF6"
token_type = "Bearer"
created_at = 2023-04-06T23:01:32.1402379+03:00

[user_data]
  id = 10185
  full_name = "Тестовый кассир"
  user_name = "Тестовый кассир"
  avatar = ""
  email = "kas@dp.not"
  role = "seller"
