access_token = "4544|sfVGBHbRvr5BOqXIN10zPtmLSXUyfkxSinHu0eIu"
token_type = "Bearer"
created_at = 2023-03-05T22:18:41.6007909+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
