access_token = "42973|iBnN6xbNfM0xbI5kySx0eJDfKTBXrE82K5swl0xZ"
token_type = "Bearer"
created_at = 2023-10-25T14:40:18.8118819+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
