access_token = "4642|AWuSZjUOof7zU7gd2nECNzCfBFoFIz2Gl1xPCeOr"
token_type = "Bearer"
created_at = 2023-04-01T19:03:07.1371598+03:00

[user_data]
  id = 8732
  full_name = "Бушкова Т.В."
  user_name = "Бушкова Т.В."
  avatar = ""
  email = "service@circus.ru"
  role = "admin"
