access_token = "4570|50Rs86mi6XYgQJCLQa8xTjJziydguWas8J1eietj"
token_type = "Bearer"
created_at = 2023-03-14T22:21:20.643762+03:00

[user_data]
  id = 8732
  full_name = "Бушкова Т.В."
  user_name = "Бушкова Т.В."
  avatar = ""
  email = "service@circus.ru"
  role = "admin"
