access_token = "4604|TAJW7vv1enQE0UObHC2MckIhBsdysBMWXbL1C2hr"
token_type = "Bearer"
created_at = 2023-03-27T06:30:22.5875087+03:00

[user_data]
  id = 8732
  full_name = "Бушкова Т.В."
  user_name = "Бушкова Т.В."
  avatar = ""
  email = "service@circus.ru"
  role = "admin"
