access_token = "42941|e45OUf55dRC0GlEygJoo7K1nMYHPLW4hjritmcgJ"
token_type = "Bearer"
created_at = 2023-10-15T11:26:21.036208+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
