access_token = "9136|p7deChNlx7LvLfXGEUfG6r5gEwEcOvdJ5bpy25ti"
token_type = "Bearer"
created_at = 2023-03-05T00:14:21.757655+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
