access_token = "6533|HL8kFJAWWCRs22kg97IM3LxzUzoyY0hYxWGUs3uO"
token_type = "Bearer"
created_at = 2023-02-13T04:21:29.7658302+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
