access_token = "43385|sFAIHh6WgG6eRJVRKXFyUreacNPuw4vTIbxdsYGO"
token_type = "Bearer"
created_at = 2023-12-16T17:15:45.008058+03:00

[user_data]
  id = 1
  full_name = "Админ"
  user_name = "Админ"
  avatar = ""
  email = "admin@domain.not"
  role = "admin"
