path = ""
com = ""
time = ""
baseurl = "https://tiplace.ru/"
polling_period = 2000000000
timeout_duration = 60000000000
update_path = "jahngeor/ticket-place"
printer_name = "Microsoft Print to PDF"
printer_service_address = "12113"
