path = ""
com = ""
time = ""
baseurl = "https://tiplace.ru/"
polling_period = "2s"
timeout_duration = "1m0s"
update_path = "jahngeor/ticket-place"
printer_name = "Microsoft Print to PDF"
printer_service_address = "12113"
